#-------------------------------
# General Site Settings
title:  Xinyi CHEN
logo: logo.svg  # logo 文件
description: Welcome to my portfolio!

#-------------------------------
# Author Settings
author:
  name: CHEN Xinyi
  image: touxiang.png # 更换为你的头像文件
  say-hello:  <strong>Welcome to my portfolio!</strong>
  bio: |
    I’m a passionate <strong>HCI er & Interactive Designer</strong>, focused on blending creativity with technology to create visually impactful and interactive web experiences. Feel free to explore my work, and don’t hesitate to reach out for collaborations or inquiries!

#-------------------------------
# Contact links
#twitter: https://twitter.com/chenxinyi # 我的 Twitter 账号链接
#facebook: https://facebook.com/chenxinyi # 我的 Facebook 账号链接
#dribbble: https://dribbble.com/chenxinyi # 我的 Dribbble 账号链接
#instagram: https://instagram.com/chenxinyi # 我的 Instagram 账号链接
#pinterest: https://pinterest.com/chenxinyi # 我的 Pinterest 账号链接

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: chenxinyi-blog # 我的 Disqus shortname

#-------------------------------
# Instagram Feed
instafeed: true  # 启用 Instagram Feed
#instagram-profile: chenxinyi # 我的 Instagram 用户名

#-------------------------------
# Google Analytics
google-analytics: UA-12345678-1  # 我的 Google Analytics 跟踪 ID

#-------------------------------
# Newsletter
mailchimp: blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
