#-------------------------------
# General Site Settings
title: "Xinyi CHEN"
logo: logo.svg  # logo file
description: Welcome to my portfolio!


#-------------------------------
# Author Settings
author:
  name: CHEN Xinyi
  image: touxiang.png # replace with your profile image
  say-hello: <strong>Welcome to my portfolio!</strong>
  bio: |
    I’m a passionate <strong>HCI er & Interactive Designer</strong>, focused on blending creativity with technology to create visually impactful and interactive web experiences. Feel free to explore my work, and don’t hesitate to reach out for collaborations or inquiries..

#-------------------------------
# Contact links
#twitter: https://twitter.com/chenxinyi # Your Twitter account link
#facebook: https://facebook.com/chenxinyi # Your Facebook account link
#dribbble: https://dribbble.com/chenxinyi # Your Dribbble account link
instagram: https://instagram.com/ # Your Instagram account link
#pinterest: https://pinterest.com/chenxinyi # Your Pinterest account link

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: chenxinyi-blog # Your Disqus shortname

#-------------------------------
# Instagram Feed
instafeed: true  # Enable Instagram Feed
instagram-profile: chenxinyi # Your Instagram username

#-------------------------------
# Google Analytics
google-analytics: UA-12345678-1  # Your Google Analytics tracking ID

#-------------------------------
# Newsletter
mailchimp: blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
